Updated community-guidelines.md
opencollective/documentation-old pull request #11
Opened 2019-05-11 05:31 UTC by ayonroy2000

Made some slight changes to make the community guidelines more clear & descriptive.

2019-05-13 04:22 UTC, alannallama commented
I am assigning this to @piamancini because she originally wrote this section.

2019-05-14 17:58 UTC, piamancini requested changes
@ayonroy2000 Thank you so much for your suggestions! They are greatly appreciated. 
I've left some comments and requested some changes.

2019-05-14 17:58 UTC, piamancini commented on about/community-guidelines.md
> +These Community guidelines take into consideration the behavior as members of the community in any form of correspondence .
Please remove the first line - it's redundant and unclear.

2019-05-14 17:58 UTC, piamancini commented on about/community-guidelines.md
> +This isn't an exhaustive list of things that you can't do. Rather, it will be a matter of healthy discussion if you take these points in the spirit in which it's intended.
Please remove this too. I agree that we can add a point about discussion, but we enforce the community guidelines. Not observing them is not ok. Happy to  review an alternative wording about the discussion.

2019-05-14 17:58 UTC, piamancini commented on about/community-guidelines.md
> +The reason we can do great things together is that each of us bring a different perspective. Whoever you are, you have a unique perspective and unique skills to contribute. Moreover as we strive towa
Please remove 'Moreover as', it is grammatically incorrect in this sentence.To make it correct, sentence needs another clause: for example: "as we strive (...) we decided to (...)".  You can start with "We strive(...)

Needs a space after the full stop and before 'So be'

2019-05-14 17:58 UTC, piamancini commented on about/community-guidelines.md
> +We have zero tolerance for trolling or harassment. Being a jerk will not get you a place in this community; it will turn people away. We don’t want that noise in the system.We know that not all of us
Needs a space after full stop and before 'We know'

Please remove "on certain points" it's not adding much and it's making the sentence a mouthful 

Please change to "(...) but we strongly believe that disagreement is not an excuse for poor behavior. It's is important to remember that a community (...)" Remove the frustration bit in the middle, it's too lengthly and the spirit of your sentence is captured in the paragraph anyway.

2019-05-14 17:58 UTC, piamancini commented on about/community-guidelines.md
> +Being an ever growing community , we always try to conduct ourselves professionally. Therefore you are required to not insult or put down other participants. Harassment and other exclusionary behavio
Please remove "Therefore(...)" we already say that above. 

We can leave the "Harassment (...) " it's a good addition.

2019-05-15 08:40 UTC, ayonroy2000 commented on about/community-guidelines.md
> +These Community guidelines take into consideration the behavior as members of the community in any form of correspondence .
Okay maam .

2019-05-15 08:40 UTC, ayonroy2000 commented on about/community-guidelines.md
> +This isn't an exhaustive list of things that you can't do. Rather, it will be a matter of healthy discussion if you take these points in the spirit in which it's intended.
Sure .

2019-05-15 08:41 UTC, ayonroy2000 commented on about/community-guidelines.md
> +The reason we can do great things together is that each of us bring a different perspective. Whoever you are, you have a unique perspective and unique skills to contribute. Moreover as we strive towa
Thanks for pointing these out. Will do the needful.

2019-05-15 08:44 UTC, ayonroy2000 commented on about/community-guidelines.md
> +We have zero tolerance for trolling or harassment. Being a jerk will not get you a place in this community; it will turn people away. We don’t want that noise in the system.We know that not all of us
Sure .

2019-05-15 08:45 UTC, ayonroy2000 commented on about/community-guidelines.md
> +Being an ever growing community , we always try to conduct ourselves professionally. Therefore you are required to not insult or put down other participants. Harassment and other exclusionary behavio
Cool

2019-05-15 08:51 UTC, ayonroy2000 commented
@piamancini have done the needful . Please review it maam .

2019-05-24 16:09 UTC, ayonroy2000 commented
@piamancini any updates ma`am ?

2020-01-31 13:11 UTC, contraexemplo commented
I'm closing this pull request as it's been open for almost a year and our documentation has changed a lot in the meantime.

2020-01-31 13:11 UTC, closed without merging