Some minor typos and link corrections in documentation
opencollective/documentation-old pull request #121
Opened 2021-05-28 05:56 UTC by SudharakaP

Related to https://github.com/opencollective/opencollective/issues/4317

2021-05-28 05:58 UTC, SudharakaP commented
@znarf : I've assigned you for the moment, but who's the best person to assign for documentation related code reviews? 😄

2021-05-28 07:07 UTC, znarf approved these changes
Everything looks good. Feel free to merge.

2021-05-28 13:34 UTC, SudharakaP commented
> Everything looks good. Feel free to merge.

@znarf : Thanks, but I'll add some more to this as I am still in progress reading the docs and I am sure I'll find many more. 😄

2021-05-30 05:36 UTC, SudharakaP commented
@znarf : This is not ready for review. Let me know if everything looks okay. 😄 This handles all simple issues I found; the more comprehensive list is given at, https://github.com/opencollective/opencollective/issues/4317.

2021-05-31 12:58 UTC, znarf requested changes
I generally prefer to link to https://opencollective.com/support instead of a mailto.

2021-05-31 13:50 UTC, SudharakaP commented
> I generally prefer to link to https://opencollective.com/support instead of a mailto.

Done. 😄 Let me know how it looks now. I've replaced almost all the mailto with the support link.

2021-05-31 13:57 UTC, znarf commented on internal/welcome-document.md
> +  email Pia directly at [pia@opencollective.co](mailto:pia@opencollective.co)
.com

2021-05-31 13:58 UTC, znarf commented on product/currencies.md
>  * JPY
Update with the currencies whitelisted in the frontend/api?

2021-05-31 14:03 UTC, SudharakaP commented on internal/welcome-document.md
> +  email Pia directly at [pia@opencollective.co](mailto:pia@opencollective.co)
Ah, thanks for pointing it out. Corrected. 👍🏽

2021-05-31 14:04 UTC, SudharakaP commented on product/currencies.md
>  * JPY
Thanks, updated from, https://github.com/opencollective/opencollective-api/blob/d43ac68141bd9401091c6e67bf42361e8dab9fc7/server/constants/currencies.ts#L174-L206

2021-06-05 03:16 UTC, SudharakaP commented
@znarf : Resolve some conflicts. Are we good to merge this? 😄 

cc: @Betree

2021-06-08 13:32 UTC, Betree approved these changes

2021-06-08 13:34 UTC, merged