Refactor: Rename subCollective(s) to relatedCollective(s)
opencollective/documentation-old pull request #70
Opened 2020-04-17 04:25 UTC by SudharakaP

This renames all subCollective(s) instances to relatedCollective(s).

Fixes https://github.com/opencollective/opencollective/issues/3040

2020-04-17 07:53 UTC, Betree requested changes

2020-04-17 07:53 UTC, Betree commented on SUMMARY.md
> +* [Relatedcollectives](collectives/relatedcollectives.md)
It's ok to not have a space in file names, but we should have one for menu entries and in text. Same goes for all the entries below.

```suggestion
* [Related collectives](collectives/relatedcollectives.md)
```

2020-04-17 13:55 UTC, SudharakaP commented on SUMMARY.md
> +* [Relatedcollectives](collectives/relatedcollectives.md)
@Betree : Ops you are right; sorry about that. I've changed it. :smile:

2020-04-17 14:16 UTC, Betree commented
Great, thanks! Let's wait for Pia's feedback on https://github.com/opencollective/opencollective/issues/3040 before moving on with this

2020-04-18 01:03 UTC, SudharakaP commented
> Great, thanks! Let's wait for Pia's feedback on [opencollective/opencollective#3040](https://github.com/opencollective/opencollective/issues/3040) before moving on with this

You are welcome. :smile:

2020-04-28 10:55 UTC, Betree commented
As per https://github.com/opencollective/opencollective/issues/3040#issuecomment-620533323, let's rather say "Connected collectives".

2020-04-28 18:52 UTC, SudharakaP commented
> As per [opencollective/opencollective#3040 (comment)](https://github.com/opencollective/opencollective/issues/3040#issuecomment-620533323), let's rather say "Connected collectives".

Done. :smile:

2020-04-29 07:57 UTC, Betree requested changes

2020-04-29 07:57 UTC, Betree commented on SUMMARY.md
> +* [Connected collectives](collectives/connectedcollectives.md)
The file itself (`subcollectives.md`) hasn't been renamed, so this will result in a `404`

2020-04-29 07:57 UTC, Betree commented on SUMMARY.md
> +  * [Connected collective queries](internal/queries/connectedcollective-queries.md)
The file itself (`subcollective-queries.md`) hasn't been renamed, so this will result in a `404`

2020-04-29 07:57 UTC, Betree commented on collectives/subcollectives.md
> +Creating connected collectives is [a manual process](../internal/queries/connectedcollective-queries.md) at the moment. If you want to do it, please send an email to [support@opencollective.com](mail
The file itself (`subcollective-queries.md`) hasn't been renamed, so this will result in a `404`

2020-04-29 10:20 UTC, SudharakaP commented on SUMMARY.md
> +* [Connected collectives](collectives/connectedcollectives.md)
Ah, seems I've missed that. Sorry. Corrected it. :smile:

2020-04-29 10:21 UTC, SudharakaP commented on SUMMARY.md
> +  * [Connected collective queries](internal/queries/connectedcollective-queries.md)
Done. :smile:

2020-04-29 10:21 UTC, SudharakaP commented on collectives/subcollectives.md
> +Creating connected collectives is [a manual process](../internal/queries/connectedcollective-queries.md) at the moment. If you want to do it, please send an email to [support@opencollective.com](mail
Corrected. :smile:

2020-04-29 15:22 UTC, merged